apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-monitor
  namespace: cpu-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-monitor
  template:
    metadata:
      labels:
        app: cpu-monitor
    spec:
      containers:
        - name: cpu-monitor
          image: 160213321344.dkr.ecr.eu-west-1.amazonaws.com/elementor:eba1d4bc2b79eefdf40c563d4b012638829cb476
          env:
            - name: KAFKA_BROKER
              value: "kafka-broker:9092"
            - name: KAFKA_TOPIC
              value: "cpu_levels"
          resources:
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-monitor
  namespace: cpu-monitor
spec:
  selector:
    app: cpu-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer