apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-monitor
  namespace: cpu-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-monitor
  template:
    metadata:
      labels:
        app: cpu-monitor
    spec:
      containers:
        - name: cpu-monitor
          image: 160213321344.dkr.ecr.eu-west-1.amazonaws.com/elementor:350aa41ab7c1e26644511a830727cf27348abb44
          env:
            - name: KAFKA_BROKER
              value: "my-kafka-cluster-kafka-brokers:9092"
            - name: KAFKA_TOPIC
              value: "cpu-levels"
          resources:
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-monitor
  namespace: cpu-monitor
spec:
  selector:
    app: cpu-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer